"""Type stubs for the Rust-backed ``kfnetlist._native`` module."""

from collections.abc import Callable, Mapping
from typing import Any, Self

class NetlistPort:
    name: str

    def __init__(self, name: str) -> None: ...
    def __hash__(self) -> int: ...
    def __lt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def to_json(self) -> str: ...
    @classmethod
    def from_json(cls, data: str) -> Self: ...
    def to_dict(self) -> dict[str, Any]: ...
    @classmethod
    def from_dict(cls, obj: dict[str, Any]) -> Self: ...

class PortRef:
    instance: str
    port: str

    def __init__(self, instance: str, port: str) -> None: ...
    @property
    def name(self) -> str: ...
    def __hash__(self) -> int: ...
    def __lt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def as_python_str(self, inst_name: str | None = ...) -> str: ...
    def to_json(self) -> str: ...
    @classmethod
    def from_json(cls, data: str) -> Self: ...
    def to_dict(self) -> dict[str, Any]: ...
    @classmethod
    def from_dict(cls, obj: dict[str, Any]) -> Self: ...

class PortArrayRef(PortRef):
    ia: int
    ib: int

    def __init__(self, instance: str, port: str, ia: int, ib: int) -> None: ...
    def __hash__(self) -> int: ...
    def __lt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def as_python_str(self, inst_name: str | None = ...) -> str: ...
    def to_json(self) -> str: ...
    @classmethod
    def from_json(cls, data: str) -> Self: ...
    def to_dict(self) -> dict[str, Any]: ...
    @classmethod
    def from_dict(cls, obj: dict[str, Any]) -> Self: ...

class NetlistArray:
    na: int
    nb: int

    def __init__(self, na: int, nb: int) -> None: ...
    def __hash__(self) -> int: ...
    def to_json(self) -> str: ...
    @classmethod
    def from_json(cls, data: str) -> Self: ...
    def to_dict(self) -> dict[str, Any]: ...
    @classmethod
    def from_dict(cls, obj: dict[str, Any]) -> Self: ...

class NetlistInstance:
    kcl: str
    component: str
    settings: dict[str, Any]
    array: NetlistArray | None
    name: str

    def __init__(
        self,
        kcl: str,
        component: str,
        settings: dict[str, Any] | None = ...,
        array: NetlistArray | None = ...,
        name: str = ...,
    ) -> None: ...
    def normalize(self) -> None: ...
    def to_json(self) -> str: ...
    @classmethod
    def from_json(cls, data: str, name: str = ...) -> Self: ...
    def to_dict(self) -> dict[str, Any]: ...
    @classmethod
    def from_dict(cls, obj: dict[str, Any], name: str = ...) -> Self: ...

NetMember = NetlistPort | PortRef | PortArrayRef

class NetIter:
    def __iter__(self) -> Self: ...
    def __next__(self) -> NetMember: ...

class Net:
    def __init__(self, members: list[NetMember] | None = ...) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> NetIter: ...
    def __getitem__(self, idx: int) -> NetMember: ...
    def __contains__(self, item: object) -> bool: ...
    def __hash__(self) -> int: ...
    def sort(self) -> None: ...
    def append(self, item: NetMember) -> None: ...
    def extend(self, items: list[NetMember]) -> None: ...
    def members(self) -> list[NetMember]: ...
    def to_json(self) -> str: ...
    @classmethod
    def from_json(cls, data: str) -> Self: ...
    def to_dict(self) -> dict[str, Any]: ...
    @classmethod
    def from_dict(cls, obj: dict[str, Any]) -> Self: ...

class Netlist:
    @property
    def instances(self) -> dict[str, NetlistInstance]: ...
    @property
    def nets(self) -> list[Net]: ...
    @property
    def ports(self) -> list[NetlistPort]: ...
    def __init__(self) -> None: ...
    def instance_names(self) -> list[str]: ...
    def has_instance(self, name: str) -> bool: ...
    def get_instance(self, name: str) -> NetlistInstance: ...
    def create_port(self, name: str) -> NetlistPort: ...
    def create_inst(
        self,
        name: str,
        kcl: str,
        component: str,
        settings: dict[str, Any] | None = ...,
        na: int = ...,
        nb: int = ...,
    ) -> NetlistInstance: ...
    def create_net(self, *ports: NetMember) -> None: ...
    def add_net(self, net: Net) -> None: ...
    def detect_opens(self) -> dict[str, Any]: ...
    def find_open_nets(self, reference: Netlist) -> list[Net]: ...
    def flatten_instances(self, names: list[str]) -> None: ...
    def normalize(
        self,
        cell_name: str | None = ...,
        equivalent_ports: Mapping[str, list[list[str]]] | None = ...,
        port_mapping: Mapping[str, Mapping[str, str]] | None = ...,
    ) -> Self: ...
    def sort(self) -> None: ...
    def to_json(self) -> str: ...
    @classmethod
    def from_json(cls, data: str) -> Self: ...
    def to_dict(self) -> dict[str, Any]: ...
    @classmethod
    def from_dict(cls, obj: dict[str, Any]) -> Self: ...

def include_from_rdb(xml: str, paths: list[str]) -> str: ...
def exclude_from_rdb(xml: str, paths: list[str]) -> str: ...
def filter_rdb(xml: str, predicate: Callable[[str], bool]) -> str: ...
